apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config
  namespace: ${namespace}
  labels:
    app: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${storage_class}
  resources:
    requests:
      storage: ${storage_size}
