apiVersion: v1
kind: Secret
metadata:
  name: pihole-admin-password
  namespace: ${namespace}
  labels:
    app: pihole
type: Opaque
data:
  # Password will be base64-encoded by OpenTofu
  password: ${admin_password_base64}
