---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: eero-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.4.200-192.168.4.210
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: eero-l2-adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - eero-pool
