---
# Homepage Secrets
# Widget API credentials (ArgoCD token)
apiVersion: v1
kind: Secret
metadata:
  name: homepage-widgets
  namespace: homepage
type: Opaque
stringData:
  HOMEPAGE_VAR_ARGOCD_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjpsb2dpbiIsImV4cCI6MTc2MzExMjY2NSwibmJmIjoxNzYzMDI2MjY1LCJpYXQiOjE3NjMwMjYyNjUsImp0aSI6ImQ5MjYzNDZjLTgxMjgtNDZiOC1iMDQwLTBhMDg3YTIxMDQ3NyJ9.4ikMwib6Ut1RLrKpU7tVIhhYU-a9iiSeC7oSqEvfOk0"
